package org.jpablo.graphexplorer.viewer.models

import com.softwaremill.quicklens.*
import org.jpablo.graphexplorer.viewer.formats.dot.ast.AttrValue
import org.jpablo.graphexplorer.viewer.formats.dot.attributes.{ClusterLabelLoc, Id, Label, LabelJust}
import org.jpablo.graphexplorer.viewer.models.Arrow.titleIdSeparator
import org.jpablo.graphexplorer.viewer.models.Attributable.idAttributeKey
import upickle.default.*

type ViewerKind = Option[String]

trait Attributable:
  def attributes: Attributes

  def label: AttrValue =
    attributes.values.getOrElse(Label.attrId, AttrValue.empty)

  def idAttr: AttrValue =
    attributes.values.getOrElse(idAttributeKey, AttrValue.empty)

object Attributable:
  val idAttributeKey = Id.attrId

case class ViewerNode private (
    id:         NodeId,
    attributes: Attributes = Attributes.empty,
    kind:       ViewerKind = None
) extends Attributable:
  def modifyAttrs = this.modify(_.attributes)

object ViewerNode:

  val defaultNodeAttributes = Attributes.of(Label -> "")

  def node(nodeId: NodeId, attributes: Attributes = Attributes.empty) =
    ViewerNode(nodeId, defaultNodeAttributes ++ attributes)

  def nodeWithId(nodeIdOrString: NodeId | String, attrs: (String, String)*) =
    val nodeId =
      nodeIdOrString match
        case id: NodeId  => id
        case str: String => NodeId(str)
    nodeId -> node(nodeId, Attributes.of(attrs*))

// ---- Edges ------

case class Arrow(
    source:     NodeId,
    target:     NodeId,
    attributes: Attributes = Attributes.empty,
    seq:        Int = 1
) extends Attributable:

  // Re-create the string used by graphviz in the `<title>` element of the SVG.
  val id = ArrowId(s"${source.value}$titleIdSeparator${target.value}:$seq")

  def nodeIds   = Set(source, target)
  def endpoints = Set(source, target)
end Arrow

object Arrow:

  val titleIdSeparator = "->"

  def arrow(t: (String, String), attrs: Map[AttributeId, AttrValue] = Map.empty, seq: Int = 1): Arrow =
    new Arrow(NodeId(t._1), NodeId(t._2), Attributes(attrs), seq)

  def arrow(s: NodeId, t: NodeId) =
    val a = Arrow(s, t)
    a.id -> a

  // example:
  // <title>A->B</title>
  val edgeTitlePattern = raw"(.+)$titleIdSeparator(.+)".r

  // Expects `title` to be the "<title>" generated by graphviz for arrows.
  // `idAttr` is used to disambiguate multiple arrows between the same nodes.
  def fromGraphvizTitle(title: String, idAttr: String): Option[Arrow] =
    title match
      case edgeTitlePattern(l, r) if l.trim.nonEmpty && r.trim.nonEmpty =>
        Some(arrow(l.trim -> r.trim, seq = idAttr.toInt))

      case _ => None

//  given arrowOrd: scala.Ordering[Arrow]:
//    def compare(x: Arrow, y: Arrow): Int =
//      val s = x.source.value `compareTo` y.source.value
//      if s != 0 then s
//      else
//        val t = x.target.value `compareTo` y.target.value
//        if t != 0 then t else x.idAttr.toString `compareTo` y.idAttr.toString
end Arrow

// ---- groups ------

case class ViewerGroup private (
    id:         GroupId,
    attributes: Attributes = Attributes.empty,
    nodeAttrs:  Attributes = Attributes.empty,
    arrowAttrs: Attributes = Attributes.empty
) extends Attributable derives CanEqual

object ViewerGroup:
  def modifyAttrs      = modify(_: ViewerGroup)(_.attributes)
  def modifyNodeAttrs  = modify(_: ViewerGroup)(_.nodeAttrs)
  def modifyArrowAttrs = modify(_: ViewerGroup)(_.arrowAttrs)

  val defaultGroupAttributes: Attributes =
    Attributes.of(
      Label           -> "",
      ClusterLabelLoc -> ClusterLabelLoc.default,
      LabelJust       -> LabelJust.default
    )

  def group(
      groupId:    GroupId,
      attributes: Attributes = Attributes.empty,
      nodeAttrs:  Attributes = Attributes.empty,
      arrowAttrs: Attributes = Attributes.empty
  ) =
    ViewerGroup(groupId, defaultGroupAttributes ++ attributes, nodeAttrs, arrowAttrs)

  def empty(groupId: GroupId) = ViewerGroup(groupId)

  def groupWithId(groupId: GroupId) =
    groupId -> ViewerGroup(groupId)

end ViewerGroup
