package org.jpablo.graphexplorer.viewer.models

import org.jpablo.graphexplorer.viewer.formats.dot.ast.AttrValue
import org.jpablo.graphexplorer.viewer.models.Arrow.titleIdSeparator
import org.jpablo.graphexplorer.viewer.models.Attributable.idAttributeKey
import upickle.default.*

type ViewerKind = Option[String]

trait Attributable:
  def attributes: Attributes

  def label: AttrValue =
    attributes.values.getOrElse(AttributeId("label"), AttrValue.empty)

  def idAttr: AttrValue =
    attributes.values.getOrElse(idAttributeKey, AttrValue.empty)

object Attributable:
  val idAttributeKey = AttributeId("id")

case class ViewerNode(
    id:         NodeId,
    attributes: Attributes = Attributes.empty,
    kind:       ViewerKind = None
) extends Attributable

object ViewerNode:

  def node(nodeIdOrString: NodeId | String, attrs: (String, String)*) =
    val nodeId =
      nodeIdOrString match
        case id: NodeId  => id
        case str: String => NodeId(str)
    nodeId -> ViewerNode(nodeId, Attributes(attrs.map((k, v) => AttributeId(k) -> AttrValue(v)).toMap))

// ---- Edges ------

case class Arrow(
    source:     NodeId,
    target:     NodeId,
    attributes: Attributes = Attributes.empty,
    seq:        Int = 1
) extends Attributable:

  // Re-create the string used by graphviz in the `<title>` element of the SVG.
  val id = ArrowId(s"${source.value}$titleIdSeparator${target.value}:$seq")

  def nodeIds = Set(source, target)
  def endpoints = Set(source, target)
end Arrow

object Arrow:

  val titleIdSeparator = "->"

  def arrow(t: (String, String), attrs: Map[AttributeId, AttrValue] = Map.empty, seq: Int = 1): Arrow =
    new Arrow(NodeId(t._1), NodeId(t._2), Attributes(attrs), seq)

  def arrow(s: NodeId, t: NodeId) =
    val a = Arrow(s, t)
    a.id -> a

  // example:
  // <title>A->B</title>
  val edgeTitlePattern = raw"(.+)$titleIdSeparator(.+)".r

  // Expects `title` to be the "<title>" generated by graphviz for arrows.
  // `idAttr` is used to disambiguate multiple arrows between the same nodes.
  def fromGraphvizTitle(title: String, idAttr: String): Option[Arrow] =
    title match
      case edgeTitlePattern(l, r) if l.trim.nonEmpty && r.trim.nonEmpty =>
        Some(arrow(l.trim -> r.trim, seq = idAttr.toInt))

      case _ => None

//  given arrowOrd: scala.Ordering[Arrow]:
//    def compare(x: Arrow, y: Arrow): Int =
//      val s = x.source.value `compareTo` y.source.value
//      if s != 0 then s
//      else
//        val t = x.target.value `compareTo` y.target.value
//        if t != 0 then t else x.idAttr.toString `compareTo` y.idAttr.toString
end Arrow

// ---- groups ------

case class ViewerGroup(
    id:         GroupId,
    attributes: Attributes = Attributes.empty,
    arrowAttrs: Attributes = Attributes.empty,
    nodeAttrs:  Attributes = Attributes.empty
) extends Attributable derives CanEqual

object ViewerGroup:
  def empty(nodeId: GroupId) = ViewerGroup(nodeId)

  def group(groupId: GroupId) =
    groupId -> ViewerGroup(groupId)

end ViewerGroup
