package org.jpablo.graphexplorer.viewer.models

import org.jpablo.graphexplorer.viewer.formats.dot.ast.AttrValue
import org.jpablo.graphexplorer.viewer.models.Arrow.titleIdSeparator
import org.jpablo.graphexplorer.viewer.models.Attributable.idAttributeKey
import org.jpablo.graphexplorer.viewer.utils.Utils
import org.jpablo.graphexplorer.viewer.utils.Utils.randomUUIDSafe
import upickle.default.*

import scala.compiletime.asMatchable

// ---- Vertices ------


case class ElementId(value: String) extends AnyVal:
  override def toString: String = value

object ElementId:
  given rw: ReadWriter[ElementId] = stringKeyRW(readwriter[String].bimap[ElementId](_.value, ElementId(_)))

  def random(): ElementId = ElementId(randomUUIDSafe().take(8))

type ViewerKind = Option[String]

trait Attributable:
  def attrs: Attributes

  def label: AttrValue =
    attrs.values.getOrElse("label", AttrValue.empty)

  def idAttr: AttrValue =
    attrs.values.getOrElse(idAttributeKey, AttrValue.empty)

//  def publicAttrs: Attributes =
//    Attributes(attrs.values -- Attributable.internal)

object Attributable:
  val idAttributeKey = "id"
//  val internal = Set(idAttributeKey)

case class ViewerNode(
    id:    ElementId,
    attrs: Attributes = Attributes.empty,
    kind:  ViewerKind = None
) extends Attributable:
  def mergeAttrs(other: Attributes): ViewerNode = copy(attrs = attrs ++ other)

object ViewerNode:
  def node(name: String, attrs: Map[String, AttrValue] = Map.empty) =
    ViewerNode(ElementId(name), Attributes(attrs))

// ---- Edges ------

case class ArrowId(value: String) extends AnyVal:
  override def toString: String = value

object ArrowId:
  def random(): ArrowId = ArrowId(Utils.randomUUIDSafe())

case class Arrow(
    source: ElementId,
    target: ElementId,
    attrs:  Attributes = Attributes.empty,
    seq:    Int = 0
) extends Attributable:

  // Re-create the string used by graphviz in the `<title>` element of the SVG.
  val id = ElementId(s"${source.value}$titleIdSeparator${target.value}:$seq")

  def nodeIds = Set(source, target, id)
  def endpoints = Set(source, target)

  def mergeAttrs(other: Attributes): Arrow = copy(attrs = attrs ++ other)

end Arrow

object Arrow:

  val titleIdSeparator = "->"

  def arrow(t: (String, String), attrs: Map[String, AttrValue] = Map.empty, seq: Int = 0): Arrow =
    new Arrow(ElementId(t._1), ElementId(t._2), Attributes(attrs), seq)

  // example:
  // <title>A->B</title>
  val edgeTitlePattern = raw"(.+)$titleIdSeparator(.+)".r

  def isArrowId(nodeId: ElementId): Boolean =
    nodeId.value.contains(titleIdSeparator)

  // Expects `title` to be the "<title>" generated by graphviz for arrows.
  // `idAttr` is used to disambiguate multiple arrows between the same nodes.
  def fromGraphvizTitle(title: String, idAttr: String): Option[Arrow] =
    title match
      case edgeTitlePattern(l, r) if l.trim.nonEmpty && r.trim.nonEmpty =>
        Some(arrow(l.trim -> r.trim, seq = idAttr.toInt))

      case _ => None

  given scala.Ordering[Arrow]:
    def compare(x: Arrow, y: Arrow): Int =
      val s = x.source.value `compareTo` y.source.value
      if s != 0 then s
      else
        val t = x.target.value `compareTo` y.target.value
        if t != 0 then t else x.idAttr.toString `compareTo` y.idAttr.toString
end Arrow

case class Attributes(values: Map[String, AttrValue]) extends AnyVal:
  def ++(other: Attributes): Attributes = Attributes(values ++ other.values)

object Attributes:
  val empty = Attributes(Map.empty)

// ---- groups ------

case class ViewerGroup(
    id: ElementId,
    // ----------------
    // We probably don't need to store the nodes and edges in the group.
//    nodes:     Set[NodeId] = Set.empty,
//    edges:     Set[NodeId] = Set.empty,
//    groups:    Set[NodeId] = Set.empty,
    // ----------------
    attrs:     Attributes = Attributes.empty,
    edgeAttrs: Attributes = Attributes.empty,
    nodeAttrs: Attributes = Attributes.empty
) extends Attributable

object ViewerGroup:
  def empty(nodeId: ElementId) = ViewerGroup(nodeId)
end ViewerGroup
