import org.scalajs.linker.interface.ModuleSplitStyle
import sbt.Test

val scala3Version    = "3.7.1"
val scalametaVersion = "4.8.2"
val laminarVersion   = "17.2.1"

Global / onChangedBuildSource := ReloadOnSourceChanges
ThisBuild / resolvers += "Sonatype OSS Snapshots" at "https://s01.oss.sonatype.org/content/repositories/snapshots"
ThisBuild / organization      := "org.jpablo"
ThisBuild / scalaVersion      := scala3Version
ThisBuild / semanticdbVersion := scalametaVersion
ThisBuild / scalacOptions ++= // Scala 3.x options
  Seq(
    "-Wsafe-init",
    "-language:implicitConversions",
    "-language:experimental.pureFunctions",
    "-language:strictEquality",
//    "-language:experimental.captureChecking",
    "-source:future",
    "-deprecation",
    "-Wunused:imports",
    "-Xfatal-warnings"
  )

lazy val shared = crossProject(JSPlatform, JVMPlatform)
  .crossType(CrossType.Pure)
  .enablePlugins(DynVerPlugin, BuildInfoPlugin)
  .in(file("shared"))
  .settings(
    name                     := "shared",
    Test / parallelExecution := false,
    buildInfoKeys            := Seq[BuildInfoKey](name, version, scalaVersion, sbtVersion),
    buildInfoPackage         := "buildinfo",
    libraryDependencies ++= Seq(
      "com.lihaoyi"                %%% "upickle"                        % "4.2.1",
      "com.lihaoyi"                %%% "upickle-implicits-named-tuples" % "4.2.1",
      "com.lihaoyi"                %%% "pprint"                         % "0.9.0",
      "com.lihaoyi"                %%% "sourcecode"                     % "0.4.2",
      "com.softwaremill.quicklens" %%% "quicklens"                      % "1.9.0",
      "org.scala-lang.modules"     %%% "scala-parser-combinators"       % "2.4.0",
      "com.lihaoyi"                %%% "fastparse"                      % "3.1.1",
      "org.scalameta"              %%% "munit"                          % "1.0.0" % Test,
      "org.scalameta"              %%% "munit-scalacheck"               % "1.0.0" % Test
    ),
    scalacOptions ++= Seq(
      "-explain",
      "-Ycheck-all-patmat",
      "-Yimports:java.lang,scala,scala.Predef,com.softwaremill.quicklens"
    ),
    testFrameworks := Seq(new TestFramework("munit.Framework"))
  ).jsSettings(
    // JS-specific settings
    scalaJSLinkerConfig ~= { _.withModuleKind(ModuleKind.ESModule) },
    libraryDependencies ++= Seq(
      "org.scala-js" %%% "scalajs-dom" % "2.8.0"
    )
  )

lazy val viewer =
  project
    .in(file("viewer"))
    .enablePlugins(ScalaJSPlugin, DynVerPlugin, BuildInfoPlugin)
    .dependsOn(shared.js)
//    .enablePlugins(ScalablyTypedConverterExternalNpmPlugin)
    .settings(
      name                            := "viewer",
      scalaJSUseMainModuleInitializer := true,
      buildInfoOptions ++= Seq(BuildInfoOption.BuildTime, BuildInfoOption.ToMap),
      scalacOptions ++= Seq(
        "-explain",
        "-Ycheck-all-patmat",
        "-Yimports:java.lang,scala,scala.Predef,org.scalajs,com.softwaremill.quicklens"
      ),
      Compile / mainClass      := Some("org.jpablo.graphexplorer.viewer.Viewer"),
      Test / parallelExecution := false,
      scalaJSLinkerConfig ~= {
        _.withModuleKind(ModuleKind.ESModule)
//          .withOutputPatterns(OutputPatterns.fromJSFile("%s.mjs"))
          .withSourceMap(true)
      },
      externalNpm := {
        scala.sys.process.Process(List("npm", "install", "--silent", "--no-audit", "--no-fund"), baseDirectory.value).!
        baseDirectory.value / ".."
      },
      libraryDependencies ++= Seq(
        "com.raquo" %%% "laminar" % laminarVersion,
//        "com.raquo"                  %%% "waypoint"    % "8.0.0",
        "com.softwaremill.quicklens"   %%% "quicklens"   % "1.9.0",
        "com.softwaremill.macwire"     %%% "macros"      % "2.6.4" % "provided",
        "io.laminext"                  %%% "fetch"       % "0.17.0",
        "org.scala-js"                 %%% "scalajs-dom" % "2.8.0",
        "com.lihaoyi"                  %%% "upickle"     % "4.2.1",
        "com.lihaoyi"                  %%% "pprint"      % "0.9.0",
        "com.softwaremill.magnolia1_3" %%% "magnolia"    % "1.3.8",
//        "com.github.sbt"             %%% "dynver"           % "5.1.0",
        "com.microsoft.playwright" % "playwright"       % "1.50.0" % Test,
        "com.microsoft.playwright" % "driver-bundle"    % "1.50.0" % Test,
        "org.seleniumhq.selenium"  % "selenium-java"    % "4.29.0" % Test,
        "org.scalameta"          %%% "munit"            % "1.0.0"  % Test,
        "org.scalameta"          %%% "munit-scalacheck" % "1.0.0"  % Test,
        // generated by scalably-typed stc (see scripts/build-viewer-netlify.sh)
        "org.scalablytyped" %%% "codemirror"                  % "6.0.1-87f1fe",
        "org.scalablytyped" %%% "codemirror__commands"        % "6.7.1-57e404",
        "org.scalablytyped" %%% "codemirror__lang-javascript" % "6.2.2-b8bf80",
        "org.scalablytyped" %%% "codemirror__view"            % "6.34.1-7b155b",
        "org.scalablytyped" %%% "jsdom"                       % "21.1.7-a2354f",
        "org.scalablytyped" %%% "viz-js__lang-dot"            % "1.0.4-def35e",
        "org.scalablytyped" %%% "viz-js__viz"                 % "3.13.0-c9123d"
      ),
      excludeDependencies ++= Seq("org.scala-lang.modules" %% "scala-collection-compat_sjs1")
      // https://www.scala-js.org/doc/project/js-environments.html
//      Test / jsEnv := new org.scalajs.jsenv.nodejs.NodeJSEnv(),
//      Test / jsEnv := new org.scalajs.jsenv.jsdomnodejs.JSDOMNodeJSEnv(),
//      Test / scalaJSLinkerConfig ~= {_.withModuleKind(ModuleKind.NoModule) },
//      Test / jsEnv := new jsenv.playwright.PWEnv(browserName = "chrome", headless = true, showLogs = true),
//      testFrameworks += new TestFramework("munit.Framework")
    )

lazy val root =
  project
    .in(file("."))
    .aggregate(viewer, shared.js, shared.jvm)
    .settings(
      name := "graph-explorer",
      welcomeMessage
    )

def welcomeMessage = onLoadMessage := {
  import scala.Console
  def header(text: String): String = s"${Console.RED}$text${Console.RESET}"

  def item(text: String): String = s"${Console.GREEN}> ${Console.CYAN}$text${Console.RESET}"

  s"""|${header(s"Graph Explorer ${version.value}")}
      |
      |Useful sbt tasks:
      |${item("~ viewer/fastLinkJS")} - compile ui
      """.stripMargin
}
