package org.jpablo.graphexplorer.graphviz.output

import org.jpablo.graphexplorer.graphviz.model.RGraph
import org.jpablo.graphexplorer.graphviz.layout.{Arrow, Coord, NodeSize, Rank, Spline, XCoord}

/** Phase 5 of the `dot` pipeline: the `svg` output writer (M7 increment 2).
  *
  * Faithful reimplementation of Graphviz 13.0.1's SVG renderer
  * (`plugin/core/gvrender_core_svg.c` + `lib/common/emit.c`/`labels.c`),
  * scoped to label-free TB poly (ellipse) nodes:
  *
  *  - header / `<svg>` / `viewBox` / `translate` (flipped-y) / background —
  *    bit-exact (derived from the goldens, cross-checked vs the C);
  *  - per node: `<ellipse>` (cx,−cy,rx=lw,ry=ht/2) + centered `<text>` whose
  *    baseline y = `−(cy + dimenY/2 − fontsize + 0.1·fontsize)` with
  *    `dimenY = fontsize·LINESPACING` (labels.c `emit_label` + textspan.c
  *    `yoffset_centerline`) — reproduces the golden exactly, not fitted;
  *  - per edge: `<path d="M..C..">` from the installed spline (y-negated) +,
  *    for a head arrow, the normal-arrowhead `<polygon>` (a[1..3] of
  *    `arrow_type_normal0`). The arrowhead's `delta_tip`/`delta_base` miter
  *    refinement is the same documented sub-2px M5 deferral.
  *
  * Numbers use Graphviz's `gvprintdouble` (`%.2f`, trailing zeros trimmed,
  * |x|<0.005 → "0"). Gated structurally + visually-close (ε) vs golden svg.
  */
object Svg:

  private val Margin       = 4.0   // GAP / default graph margin (pt)
  private val FontSize     = 14.0  // DEFAULT_FONTSIZE
  private val LineSpacing  = 1.20  // LINESPACING
  private val ArrowLen     = 10.0  // ARROW_LENGTH (× arrowsize)
  private val GvVersion    = "13.0.1 (20250615.1724)"

  /** gvprintdouble: %.2f, trim trailing zeros & point, snap near-zero to 0. */
  private[output] def d2(x: Double): String =
    if x > -0.005 && x < 0.005 then "0"
    else
      val bd = BigDecimal(x).setScale(2, BigDecimal.RoundingMode.HALF_UP)
      var s  = bd.bigDecimal.toPlainString
      if s.contains('.') then
        s = s.reverse.dropWhile(_ == '0').dropWhile(_ == '.').reverse
      if s == "-0" then "0" else s

  /** Graphviz xml_string for SVG: escape & < > " and '-' (avoids `--` in
    * XML comments; matches `a&#45;&gt;b` in titles/comments). */
  private def xml(s: String): String =
    val b = new StringBuilder
    s.foreach {
      case '&' => b ++= "&amp;"
      case '<' => b ++= "&lt;"
      case '>' => b ++= "&gt;"
      case '"' => b ++= "&quot;"
      case '-' => b ++= "&#45;"
      case c   => b += c
    }
    b.toString


  def svg(g: RGraph): String =
    val byId       = g.nodes.iterator.map(n => n.id -> n).toMap
    val xs         = XCoord.xCoords(g)
    val (_, yOf)   = Coord.rankY(g)
    val ranks      = Rank.assign(g)
    val spl        = Spline.splinesEx(g)
    val labelPos   = Spline.labelPositions(g)

    // graph bbox = the shared exact node-extent box (Output.bbox /
    // position.c dot_compute_bb) — NO spline, NO floor/ceil. `<svg
    // width/height>`/viewBox are the ceil'd int canvas; the `translate`
    // and background polygon keep the exact float (gv: int canvas, 2-dp bb).
    val (lxPt, lyPt, uxPt, uyPt) = Output.bbox(g)
    val (lx, ly, ux, uy) = (lxPt.value, lyPt.value, uxPt.value, uyPt.value)
    // gv canvas: ROUND((pageSize + 2*margin) * dpi/72) with dpi=72 (emit.c:1288)
    // ⇒ ROUND(bb + 2*margin). (Was ceil — same for ≥.5 fractions; triangle
    // 69.291 → 69, not ceil's 70.)
    val bbW = ux - lx; val bbH = uy - ly
    val w   = Output.gvRound(bbW + 2 * Margin).toInt
    val h   = Output.gvRound(bbH + 2 * Margin).toInt
    val trX = Margin - lx
    val trY = uy + Margin

    val sb = new StringBuilder
    sb ++= "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
    sb ++= "<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n"
    sb ++= " \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n"
    sb ++= s"<!-- Generated by graphviz version $GvVersion\n -->\n"
    // `\E`/`\N`/title substitution (labels.c): a *named* graph emits the
    // `Title:` comment + a graph `<title>`; an anonymous graph (`%1`) emits
    // neither. (g.name == the graph id; None ⇒ anonymous.)
    val gname = g.name
    sb ++= (gname match
      case Some(nm) => s"<!-- Title: ${xml(nm)} Pages: 1 -->\n"
      case None     => "<!-- Pages: 1 -->\n")
    sb ++= s"""<svg width="${w}pt" height="${h}pt"\n"""
    sb ++= s""" viewBox="0.00 0.00 ${w}.00 ${h}.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">\n"""
    sb ++= s"""<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(${d2(trX)} ${d2(trY)})">\n"""
    gname.foreach(nm => sb ++= s"<title>${xml(nm)}</title>\n")
    // background canvas
    val bx0 = lx - Margin; val bx1 = ux + Margin
    val by0 = Margin; val by1 = -(uy + Margin)
    sb ++= s"""<polygon fill="white" stroke="none" points="${d2(bx0)},${d2(by0)} ${d2(bx0)},${d2(by1)} ${d2(bx1)},${d2(by1)} ${d2(bx1)},${d2(by0)} ${d2(bx0)},${d2(by0)}"/>\n"""

    // nodes (declaration order)
    val dimY = FontSize * LineSpacing
    def textAt(cx: Double, cyc: Double, s: String, fill: String = ""): String =
      val ty = -(cyc + dimY / 2.0 - FontSize + 0.1 * FontSize)
      val f  = if fill.nonEmpty then s""" fill="$fill"""" else "" // fontcolor
      s"""<text xml:space="preserve" text-anchor="middle" x="${d2(cx)}" y="${d2(ty)}" font-family="Times,serif" font-size="14.00"$f>${xml(s)}</text>\n"""

    // ── HTML-like label rendering (emit_html_txt / emit_htextspans) ──────────
    /** Render an HTML text block centred at (cx, cyc): each line is left-anchored
      * at its justified x, items laid left-to-right with per-run font styling.
      * The baseline reuses the quoted-label placement (gv's simple-text path);
      * multi-line stacks each line down by its height from the block top. */
    def htmlText(cx: Double, cyc: Double, block: org.jpablo.graphexplorer.graphviz.html.HtmlText,
                 defColor: String, alignWidth: Double,
                 defAlign: org.jpablo.graphexplorer.graphviz.html.HtmlAlign): String =
      import org.jpablo.graphexplorer.graphviz.html.{HtmlLayout, HtmlAlign}
      val out   = new StringBuilder
      val lines = block.spans.map(sp => (sp, HtmlLayout.lineMetrics(sp, FontSize, "Times")))
      // Justify lines within `alignWidth` (the cell content area, or the text
      // box itself for a standalone label); each span's own align wins over the
      // inherited default.
      val boxW  = alignWidth
      val boxH  = lines.map(_._2._2).sum
      // `simple` (size_html_txt): ≤1 item/span, no style flags, uniform font.
      // Non-simple sets yoffset_centerline=1 uniformly (emit_htextspans), which
      // lands each baseline 1pt lower than the simple/quoted-label placement.
      val allItems = block.spans.flatMap(_.items)
      def flagged(f: org.jpablo.graphexplorer.graphviz.html.HtmlFont): Boolean =
        f.bold || f.italic || f.underline || f.strike || f.sub || f.sup
      val simple = block.spans.forall(_.items.sizeIs <= 1) && allItems.forall(it => !flagged(it.font)) &&
        allItems.map(it => (it.font.size, it.font.name)).distinct.sizeIs <= 1
      val yFix = if simple then 0.0 else 1.0
      // Block centred at cyc (world y-up). Each line's centre y descends by its
      // own height; the baseline is that centre offset like a quoted label.
      var lineTop = cyc + boxH / 2.0
      lines.foreach { case (sp, (lineW, lineH)) =>
        val lineCy = lineTop - lineH / 2.0
        val ty     = -(lineCy + lineH / 2.0 - FontSize + 0.1 * FontSize) - yFix
        val x0 = sp.align.getOrElse(defAlign) match
          case HtmlAlign.Left  => cx - boxW / 2.0
          case HtmlAlign.Right => cx + boxW / 2.0 - lineW
          case _               => cx - lineW / 2.0
        var xi = x0
        sp.items.foreach { it =>
          val fs   = it.font.size.getOrElse(FontSize.toDouble)
          val nm   = it.font.name.getOrElse("Times")
          val bold = it.font.bold || nm.toLowerCase.contains("bold")
          val ital = it.font.italic || nm.toLowerCase.contains("italic") || nm.toLowerCase.contains("oblique")
          val w    = HtmlLayout.itemWidth(it, FontSize, "Times")
          val wgt  = if bold then " font-weight=\"bold\"" else ""
          val sty  = if ital then " font-style=\"italic\"" else ""
          val col  = it.font.color.orElse(Option(defColor).filter(_.nonEmpty))
          val f    = col.map(c => s""" fill="$c"""").getOrElse("")
          val dec  = if it.font.underline then " text-decoration=\"underline\"" else ""
          out ++= s"""<text xml:space="preserve" text-anchor="start" x="${d2(xi)}" y="${d2(ty)}" font-family="Times,serif"$wgt$sty font-size="${f"$fs%.2f"}"$f$dec>${xml(it.str)}</text>\n"""
          xi += w
        }
        lineTop -= lineH
      }
      out.toString

    /** Render an HTML `<table>` centred at (cx, cyc): cells first (border box +
      * centred content), then the outer table border (emit order: cell, content,
      * …, table border last — matches gv). Coords are table-local y-up + centre. */
    def htmlTable(cx: Double, cyc: Double, tbl: org.jpablo.graphexplorer.graphviz.html.HtmlTable,
                  defColor: String): String =
      import org.jpablo.graphexplorer.graphviz.html.{HtmlTableLayout, HtmlLabel, HtmlAlign}
      val laid = HtmlTableLayout.layout(tbl, FontSize, "Times")
      val out  = new StringBuilder
      // box polygon in world coords: LL, UL, UR, LR, LL (gvrender_box order).
      def boxPoly(b: HtmlTableLayout.BoxLocal): String =
        val (l, r) = (cx + b.llx, cx + b.urx)
        val (lo, hi) = (cyc + b.lly, cyc + b.ury)
        s"${d2(l)},${d2(-lo)} ${d2(l)},${d2(-hi)} ${d2(r)},${d2(-hi)} ${d2(r)},${d2(-lo)} ${d2(l)},${d2(-lo)}"
      // table bgcolor fills the whole table box first (behind cells).
      val tblBox = HtmlTableLayout.BoxLocal(-laid.width / 2.0, -laid.height / 2.0, laid.width / 2.0, laid.height / 2.0)
      tbl.attrs.get("bgcolor").foreach { bg =>
        out ++= s"""<polygon fill="$bg" stroke="none" points="${boxPoly(tblBox)}"/>\n"""
      }
      laid.cells.foreach { pc =>
        // cell bgcolor fill (no stroke) before the border.
        pc.cell.attrs.get("bgcolor").foreach { bg =>
          out ++= s"""<polygon fill="$bg" stroke="none" points="${boxPoly(pc.box)}"/>\n"""
        }
        if pc.cellBorder > 0 then
          out ++= s"""<polygon fill="none" stroke="black" points="${boxPoly(pc.box)}"/>\n"""
        val ccx = cx + pc.contentBox.cx
        // valign positions the content box within the (taller) content area:
        // top ⇒ content top at the area top, bottom ⇒ content bottom at the
        // area bottom, middle (default) ⇒ centred. (pos_html_cell alignment.)
        val (_, contentH) = org.jpablo.graphexplorer.graphviz.html.HtmlLayout.size(pc.cell.content, FontSize, "Times")
        val ccy = pc.cell.attrs.get("valign").map(_.toLowerCase) match
          case Some("top")    => cyc + pc.contentBox.ury - contentH / 2.0
          case Some("bottom") => cyc + pc.contentBox.lly + contentH / 2.0
          case _              => cyc + pc.contentBox.cy
        pc.cell.content match
          case HtmlLabel.Text(block)  =>
            val cw = pc.contentBox.urx - pc.contentBox.llx
            val al = pc.cell.attrs.get("align").map(_.toLowerCase) match
              case Some("left")  => HtmlAlign.Left
              case Some("right") => HtmlAlign.Right
              case _             => HtmlAlign.Center
            out ++= htmlText(ccx, ccy, block, defColor, cw, al)
          case HtmlLabel.Table(inner) => out ++= htmlTable(ccx, ccy, inner, defColor)
      }
      if laid.border > 0 then
        out ++= s"""<polygon fill="none" stroke="black" points="${boxPoly(tblBox)}"/>\n"""
      out.toString

    // record_gencode + gen_fields (shapes.c): outer box polygon, then per
    // table the inter-child separator polylines + per leaf the field text.
    // Boxes are node-local (centre origin, y-up) — add the node centre.
    def genFields(f: org.jpablo.graphexplorer.graphviz.layout.RecordLabel.Field,
                   ncx: Double, ncy: Double): Unit =
      if f.isLeaf then
        f.text.filter(_.nonEmpty).foreach { t =>
          sb ++= textAt(ncx + (f.llx + f.urx) / 2.0, ncy + (f.lly + f.ury) / 2.0, t)
        }
      else
        f.flds.iterator.zipWithIndex.foreach { case (c, k) =>
          if k > 0 then
            val (a0, a1) =
              if f.lr then ((c.llx, c.lly), (c.llx, c.ury)) // vertical sep
              else        ((c.llx, c.ury), (c.urx, c.ury))  // horizontal sep
            sb ++= s"""<polyline fill="none" stroke="black" points="${d2(ncx + a0._1)},${d2(-(ncy + a0._2))} ${d2(ncx + a1._1)},${d2(-(ncy + a1._2))}"/>\n"""
          genFields(c, ncx, ncy)
        }

    val op      = if g.directed then "->" else "--"
    val nodeIdx = g.nodes.iterator.map(_.id).zipWithIndex.toMap

    def emitNode(i: Int): Unit =
      val n = g.nodes(i)
      for xPt <- xs.get(n.id); sz <- NodeSize.nodeSize(n, g) do
        val x    = xPt.value
        val cy   = yOf(ranks(n.id)).value
        sb ++= s"<!-- ${xml(n.id)} -->\n"
        sb ++= s"""<g id="node${i + 1}" class="node">\n"""
        sb ++= s"<title>${xml(n.id)}</title>\n"
        NodeSize.recordLayout(n, g) match
          case Some(root) =>
            // outer record box (gvrender_box → svg polygon, LL/UL/UR/LR/LL)
            val (llx, lly) = (x + root.llx, cy + root.lly)
            val (urx, ury) = (x + root.urx, cy + root.ury)
            sb ++= s"""<polygon fill="none" stroke="black" points="${d2(llx)},${d2(-lly)} ${d2(llx)},${d2(-ury)} ${d2(urx)},${d2(-ury)} ${d2(urx)},${d2(-lly)} ${d2(llx)},${d2(-lly)}"/>\n"""
            genFields(root, x, cy)
          case None =>
            val rx  = sz.halfWidthPt.value
            val ry  = sz.halfHeightPt.value
            val lbl = n.attrs.get("label").filter(_ != "\\N").getOrElse(n.id)
            // gv node style: `filled` ⇒ fill = fillcolor|color|lightgrey, else
            // "none"; stroke = pencolor (`color`), default black; text = fontcolor.
            val styles = n.attrs.get("style").map(_.split(",").iterator.map(_.trim).toSet).getOrElse(Set.empty)
            val fill =
              if styles.contains("filled") then
                n.attrs.get("fillcolor").orElse(n.attrs.get("color")).getOrElse("lightgrey")
              else "none"
            val stroke = n.attrs.get("color").getOrElse("black")
            // box-family shapes render as a rectangle <polygon> (corners
            // UR,UL,LL,LR,UR in flipped-y); `style=rounded` ⇒ a <path> with
            // RBCONST=12 corner arcs (shapes.c round_corners); else ellipse.
            val boxLike   = Set("box", "rect", "rectangle", "square")
            val shapeName = n.attrs.get("shape").getOrElse("")
            val noShape   = Set("plaintext", "none", "plain").contains(shapeName)
            if noShape then () // plaintext/none/plain draw no shape border
            else if boxLike.contains(shapeName) then
              val (l, rr)  = (x - rx, x + rx)
              val (t, b)   = (-(cy + ry), -(cy - ry))
              if styles.contains("rounded") then
                val c = math.min(12.0, math.min(rx, ry)) // RBCONST, clamped
                // 4 straight edges (cubic with endpoint controls) + 4 corner
                // arcs (control points at c/2), CW from the top edge.
                val segs = Seq(
                  s"${d2(rr - c)},${d2(t)} ${d2(l + c)},${d2(t)} ${d2(l + c)},${d2(t)}",
                  s"${d2(l + c / 2)},${d2(t)} ${d2(l)},${d2(t + c / 2)} ${d2(l)},${d2(t + c)}",
                  s"${d2(l)},${d2(t + c)} ${d2(l)},${d2(b - c)} ${d2(l)},${d2(b - c)}",
                  s"${d2(l)},${d2(b - c / 2)} ${d2(l + c / 2)},${d2(b)} ${d2(l + c)},${d2(b)}",
                  s"${d2(l + c)},${d2(b)} ${d2(rr - c)},${d2(b)} ${d2(rr - c)},${d2(b)}",
                  s"${d2(rr - c / 2)},${d2(b)} ${d2(rr)},${d2(b - c / 2)} ${d2(rr)},${d2(b - c)}",
                  s"${d2(rr)},${d2(b - c)} ${d2(rr)},${d2(t + c)} ${d2(rr)},${d2(t + c)}",
                  s"${d2(rr)},${d2(t + c / 2)} ${d2(rr - c / 2)},${d2(t)} ${d2(rr - c)},${d2(t)}"
                )
                sb ++= s"""<path fill="$fill" stroke="$stroke" d="M${d2(rr - c)},${d2(t)}C${segs.mkString(" ")}"/>\n"""
              else
                sb ++= s"""<polygon fill="$fill" stroke="$stroke" points="${d2(rr)},${d2(t)} ${d2(l)},${d2(t)} ${d2(l)},${d2(b)} ${d2(rr)},${d2(b)} ${d2(rr)},${d2(t)}"/>\n"""
            else
              // Convex builtin polygon (diamond/triangle/hexagon/…): poly_gencode
              // draws periphery-0 vertices translated by the node centre; SVG
              // negates y. Points are listed in gv's generated order, closed by
              // repeating the first vertex.
              NodeSize.polygon(n, g) match
                case Some(poly) =>
                  val pts    = poly.vertices.map((vx, vy) => s"${d2(x + vx)},${d2(-(cy + vy))}")
                  val closed = (pts :+ pts.head).mkString(" ")
                  sb ++= s"""<polygon fill="$fill" stroke="$stroke" points="$closed"/>\n"""
                case None =>
                  // ellipse family: draw `peripheries` concentric rings from the
                  // inner (label-fit) outward; each ring is GAP larger (poly_gencode
                  // draws periphery 0 first). doublecircle ⇒ 2 rings (18, 22).
                  val peris = NodeSize.peripheriesOf(n)
                  val gap   = 4.0 // const.h GAP
                  var j     = 0
                  while j < peris do
                    val off = gap * (peris - 1 - j) // inner ring is smallest
                    sb ++= s"""<ellipse fill="$fill" stroke="$stroke" cx="${d2(x)}" cy="${d2(-cy)}" rx="${d2(rx - off)}" ry="${d2(ry - off)}"/>\n"""
                    j += 1
            // HTML-like label ⇒ render the parsed content; else the plain text.
            if n.attrs.isHtml("label") then
              import org.jpablo.graphexplorer.graphviz.html.{HtmlParser, HtmlLabel}
              HtmlParser.parse(n.attrs.getOrElse("label", "")) match
                case Some(HtmlLabel.Text(block)) =>
                  val bw = org.jpablo.graphexplorer.graphviz.html.HtmlLayout.textSize(block, FontSize, "Times")._1
                  sb ++= htmlText(x, cy, block, n.attrs.get("fontcolor").getOrElse(""), bw,
                    org.jpablo.graphexplorer.graphviz.html.HtmlAlign.Center)
                case Some(HtmlLabel.Table(tbl)) =>
                  sb ++= htmlTable(x, cy, tbl, n.attrs.get("fontcolor").getOrElse(""))
                case None                     => sb ++= textAt(x, cy, lbl, n.attrs.get("fontcolor").getOrElse(""))
            else
              sb ++= textAt(x, cy, lbl, n.attrs.get("fontcolor").getOrElse(""))
        sb ++= "</g>\n"

    def emitEdge(ix: Int, ei: Int): Unit =
      val e = g.edges(ix)
      spl.get(ix).foreach { es =>
          val pts = es.pts
          // emit.c: the edge *comment* is portless (agnameof tail/head);
          // the `<title>` is the `\E` expansion = tail[:port]op head[:port]
          // where port = chkPort `.name` (after the first ':' if any, else
          // whole) = compass when a field+compass was given (`f2:s` ⇒ `s`).
          val comment = s"${e.tail}$op${e.head}"
          val tp = e.tailPortName.fold("")(":" + _)
          val hp = e.headPortName.fold("")(":" + _)
          val label = s"${e.tail}$tp$op${e.head}$hp"
          sb ++= s"<!-- ${xml(comment)} -->\n"
          sb ++= s"""<g id="edge$ei" class="edge">\n"""
          sb ++= s"<title>${xml(label)}</title>\n"
          val head = pts.head
          val rest = pts.tail.map(p => s"${d2(p.x)},${d2(-p.y)}").mkString(" ")
          // gv edge: stroke = `color` (default black); `dashed`/`dotted` style
          // ⇒ stroke-dasharray. Arrowhead polygon takes the same stroke+fill.
          val eStroke = e.attrs.get("color").getOrElse("black")
          val eStyles = e.attrs.get("style").map(_.split(",").iterator.map(_.trim).toSet).getOrElse(Set.empty)
          val dash =
            if eStyles.contains("dashed") then """ stroke-dasharray="5,2""""
            else if eStyles.contains("dotted") then """ stroke-dasharray="1,5""""
            else ""
          sb ++= s"""<path fill="none" stroke="$eStroke"$dash d="M${d2(head.x)},${d2(-head.y)}C$rest"/>\n"""
          if g.directed then
            es.ep.foreach { tip =>
              val base = pts.last
              val dx = base.x - tip.x; val dy = base.y - tip.y
              val len = math.hypot(dx, dy)
              if len > 1e-9 then
                val pw = e.attrs.get("penwidth").flatMap(_.toDoubleOption).getOrElse(1.0)
                val as = e.attrs.get("arrowsize").flatMap(_.toDoubleOption).getOrElse(1.0)
                val mag = ArrowLen * as
                val u   = (dx / len * mag, dy / len * mag)
                val (a1, a2, a3, _) = Arrow.normal0((tip.x, tip.y), u, pw)
                def pt(p: (Double, Double)) = s"${d2(p._1)},${d2(-p._2)}"
                sb ++= s"""<polygon fill="$eStroke" stroke="$eStroke" points="${pt(a1)} ${pt(a2)} ${pt(a3)} ${pt(a1)}"/>\n"""
            }
          // edge label text at its lp (make_chain label_vnode)
          e.attrs.get("label").filter(_.nonEmpty).foreach { lbl =>
            labelPos.get(ix).foreach(lp => sb ++= textAt(lp.x, lp.y, lbl, e.attrs.get("fontcolor").getOrElse("")))
          }
          sb ++= "</g>\n"
        }

    // gv svg emit order: for each node (first-mention order) emit it, then per
    // out-edge emit the head node (if unseen) then the edge — so nodes/edges
    // interleave (a node appears just before the first edge that closes on it).
    // root graph label (do_graph_label): centered horizontally, single line,
    // bottom labelloc (default) at GAP + boxHeight/2. Emitted after the
    // background, before the nodes. (Custom fontsize / multi-line / top =
    // tracked follow-ups.)
    g.rootAttrs.get("label").filter(_.nonEmpty).foreach { lbl =>
      val lh = NodeSize.labelHeightPt(lbl, FontSize, g.name.getOrElse(""))
      sb ++= textAt((lx + ux) / 2.0, 4.0 + lh / 2.0, lbl)
    }

    // svg `id="edgeN"` = the edge's declaration (AGSEQ) index + 1 (g.edges is
    // in declaration order) — decoupled from the interleaved *emit* order.
    val emitted = scala.collection.mutable.Set.empty[String]
    def ensureNode(id: String): Unit =
      nodeIdx.get(id).foreach(i => if !emitted(id) then { emitted += id; emitNode(i) })
    g.nodes.indices.foreach { ti =>
      ensureNode(g.nodes(ti).id)
      g.edges.indices.filter(ix => g.edges(ix).tail == g.nodes(ti).id).foreach { ix =>
        ensureNode(g.edges(ix).head)
        emitEdge(ix, ix + 1)
      }
    }
    g.nodes.indices.foreach(i => ensureNode(g.nodes(i).id)) // any isolated nodes

    sb ++= "</g>\n</svg>\n"
    sb.toString

end Svg
