package org.jpablo.graphexplorer.viewer.backends

import munit.FunSuite
import org.jpablo.graphexplorer.graphviz.Graphviz as ScalaGraphviz
import org.jpablo.graphexplorer.viewer.backends.UnmodeledContent.*
import org.jpablo.graphexplorer.viewer.backends.graphviz.vizjs.simplegraph.{SimpleGraph, toViewerGraph as dotJsonToViewerGraph}
import org.jpablo.graphexplorer.viewer.backends.mermaid.{MermaidFlowchartParser, toViewerGraph as mermaidToViewerGraph, viewerGraphToMermaidText}
import org.jpablo.graphexplorer.viewer.graph.ViewerGraph.viewerGraphToText
import upickle.default.read

/** The content that a round trip through the graph model drops.
  *
  * A canvas edit prints the whole graph again. The printers keep what the graph
  * models, and nothing else. `RoundTripLoss.scan` names what a document has that
  * the printer will not write back, so that a viewer can refuse an edit that
  * would drop it from a file.
  *
  * Each case below was observed with `gx run <file> set-attribute`, which uses
  * the same printers as the viewer. The negative cases matter as much: a false
  * alarm blocks canvas edits on a document that would round-trip cleanly.
  */
class RoundTripLossSpec extends FunSuite:

  private def dot(text: String)     = RoundTripLoss.scan(text, DiagramFormat.DOT)
  private def mermaid(text: String) = RoundTripLoss.scan(text, DiagramFormat.Mermaid)

  // ------------------------------------------------------------------ DOT

  test("dot: a line comment"):
    assertEquals(dot("digraph G {\n  a -> b  // reads\n}"), Set(Comments))

  test("dot: a block comment"):
    assertEquals(dot("digraph G {\n  /* the API layer */\n  a -> b\n}"), Set(Comments))

  test("dot: a comment before the graph"):
    assertEquals(dot("// generated by hand\ndigraph G { a -> b }"), Set(Comments))

  test("dot: a preprocessor line"):
    // Graphviz ignores a line that starts with `#`, and so does the parser.
    assertEquals(dot("# 1 \"deps.gv\"\ndigraph G {\n  a -> b\n}"), Set(Comments))

  test("dot: `strict`"):
    assertEquals(dot("strict digraph G { a -> b }"), Set(StrictKeyword))

  test("dot: `strict` in any letter case, as DOT keywords are"):
    assertEquals(dot("STRICT graph G { a -- b }"), Set(StrictKeyword))

  test("dot: comments and `strict` together"):
    assertEquals(dot("// header\nstrict digraph G { a -> b }"), Set(Comments, StrictKeyword))

  test("dot: comment markers inside a quoted string are not comments"):
    val text =
      """digraph G {
        |  a [URL="http://example.com/x", label="/* no */", color="#ff0000"]
        |  b [tooltip="say \"//\" twice"]
        |}""".stripMargin
    assertEquals(dot(text), Set.empty)

  test("dot: a line that starts with `#` inside a quoted string is not a preprocessor line"):
    assertEquals(dot("digraph G {\n  a [label=\"first\n# second\"]\n}"), Set.empty)

  test("dot: comment markers inside an HTML label are not comments"):
    assertEquals(dot("""digraph G { a [label=<<a href="http://x/y">/*b*/</a>>] }"""), Set.empty)

  test("dot: a name that contains `strict` is not the keyword"):
    assertEquals(dot("digraph G { strictness -> strict_mode }"), Set.empty)

  test("dot: a plain document has nothing to drop"):
    assertEquals(dot("digraph Deps {\n  node [shape=box]\n  api -> db\n}"), Set.empty)

  // -------------------------------------------------------------- Mermaid

  test("mermaid: a comment line"):
    assertEquals(mermaid("flowchart LR\n  %% the api layer\n  a --> b"), Set(Comments))

  test("mermaid: an init directive"):
    assertEquals(mermaid("%%{init: {\"theme\": \"dark\"}}%%\nflowchart LR\n  a --> b"), Set(Directives))

  test("mermaid: click lines, in both forms"):
    assertEquals(mermaid("flowchart LR\n  a --> b\n  click a \"https://example.com\" \"Open\""), Set(ClickHandlers))
    assertEquals(mermaid("flowchart LR\n  a --> b\n  click b call callback()"), Set(ClickHandlers))

  test("mermaid: accessibility text"):
    assertEquals(mermaid("flowchart LR\n  accTitle: Deps\n  a --> b"), Set(AccessibilityText))
    assertEquals(mermaid("flowchart LR\n  accDescr {\n    The deps\n  }\n  a --> b"), Set(AccessibilityText))

  test("mermaid: a direction inside a subgraph"):
    assertEquals(mermaid("flowchart TD\n  subgraph s\n    direction LR\n    a --> b\n  end"), Set(SubgraphDirection))

  test("mermaid: several kinds at once"):
    val text = "%%{init: {\"theme\": \"dark\"}}%%\nflowchart LR\n  %% note\n  a --> b\n  click a \"https://x\""
    assertEquals(mermaid(text), Set(Directives, Comments, ClickHandlers))

  test("mermaid: what the model keeps is not flagged"):
    val text =
      """---
        |title: Pipeline
        |---
        |flowchart TD
        |  subgraph svc [Services]
        |    api:::hot --> db
        |  end
        |  web -->|calls| api
        |  classDef hot fill:#f96,stroke:#333
        |  class db hot
        |  linkStyle 0 stroke:#0f0
        |  style web fill:#ccc""".stripMargin
    assertEquals(mermaid(text), Set.empty)

  test("mermaid: `%%` inside a label is not a comment"):
    assertEquals(mermaid("flowchart LR\n  a[\"50%% off\"] --> b"), Set.empty)

  test("mermaid: a node whose name starts with `click` is not a click line"):
    assertEquals(mermaid("flowchart LR\n  clicked --> b"), Set.empty)

  // ------------------------------------------------ the printers themselves

  test("the DOT printer's own output is never flagged"):
    // Otherwise a document that a canvas edit wrote could never be edited on
    // the canvas again.
    val samples = List(
      "// header\nstrict digraph G {\n  /* c */ a -> b  // d\n}",
      "digraph D {\n  node [shape=box, color=\"#00f\"]\n  subgraph cluster_x { label=\"X\"; a; b }\n  a -> b [URL=\"http://e.com\"]\n}",
      "digraph H { h [label=<<b>bold</b>>] }",
      "graph U { a -- b }"
    )
    for text <- samples do
      val json    = ScalaGraphviz.structureJson(text).fold(e => fail(s"could not parse $text: $e"), identity)
      val printed = viewerGraphToText(dotJsonToViewerGraph(read[SimpleGraph](json)), omitInternal = true)
      assertEquals(dot(printed), Set.empty, s"the printer's output is flagged:\n$printed")

  test("the Mermaid printer's own output is never flagged"):
    val samples = List(
      "flowchart LR\n  %% note\n  api[API] --> db[(DB)]\n  click api \"https://x\"",
      "---\ntitle: Pipeline\n---\nflowchart TD\n  subgraph svc [Services]\n    direction LR\n    api:::hot --> db\n  end\n  web -->|calls| api\n  classDef hot fill:#f96\n  linkStyle 0 stroke:#0f0\n  style web fill:#ccc"
    )
    for text <- samples do
      val graph   = MermaidFlowchartParser.parse(text).fold(e => fail(s"could not parse $text: $e"), identity)
      val printed = viewerGraphToMermaidText(mermaidToViewerGraph(graph))
      assertEquals(mermaid(printed), Set.empty, s"the printer's output is flagged:\n$printed")
