#!/usr/bin/env python3
"""Generate pure-Scala builtin font-metric tables from Graphviz's textspan_lut.c.

This transcribes *data* (per-character advance-width tables for the standard
PostScript font families) from the pinned Graphviz 13.0.1 source — it does NOT
copy algorithm code. Provenance: lib/common/textspan_lut.c, EPL-2.0.

  python3 graphviz/oracle/gen_font_metrics.py \
      /Users/jpablo/GitHub/graphviz-1301

Emits: graphviz/shared/.../graphviz/metrics/FontMetricsTables.scala

Every family in textspan_lut.c is emitted (the 3 core PostScript families
plus gv's hard-coded web-font metrics — Verdana, Georgia, Trebuchet, etc.;
the fallback for unknown names is Times, first in the list). Re-run if the
pinned Graphviz is ever re-pinned.
"""
import re, sys, pathlib

# ALL families from textspan_lut.c — gv ships hard-coded metrics for the 3
# core PostScript families PLUS common web fonts (Verdana, Georgia, Trebuchet,
# Consolas, DejaVu Sans, Nunito, OpenSans, Calibri); siblings.gv uses Verdana.
WANT = None  # None = emit every family

def split_top_level(s, open_ch="{", close_ch="}"):
    """Yield depth-1 element substrings of a brace-delimited C array body."""
    depth, start, out = 0, None, []
    for i, c in enumerate(s):
        if c == open_ch:
            depth += 1
            if depth == 1:
                start = i + 1
        elif c == close_ch:
            if depth == 1:
                out.append(s[start:i])
            depth -= 1
    return out

def main():
    gv = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "/Users/jpablo/GitHub/graphviz-1301")
    src = (gv / "lib/common/textspan_lut.c").read_text()

    m = re.search(r"all_font_metrics\[\]\s*=\s*\{", src)
    body_start = m.end() - 1
    # balanced-brace slice of the whole array initialiser
    depth = 0
    for i in range(body_start, len(src)):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                array_body = src[body_start + 1 : i]
                break

    families = []
    for elem in split_top_level(array_body):
        aliases = re.findall(r'"([^"]*)"', elem.split("}", 1)[0] if "}" in elem else elem)
        # aliases live inside the first (const char *[]){...} group
        alias_grp = re.search(r"\(const char \*\[\]\)\s*\{([^}]*)\}", elem).group(1)
        aliases = re.findall(r'"([^"]*)"', alias_grp)
        if WANT is not None and not (set(a.lower() for a in aliases) & WANT):
            continue
        rest = elem[re.search(r"\(const char \*\[\]\)\s*\{[^}]*\}", elem).end():]
        upm = int(re.search(r",\s*(\d+)\s*,", rest).group(1))
        arrays = split_top_level(rest)  # the four short[128] initialisers
        nums = []
        for a in arrays[:4]:
            vals = [int(x) for x in re.findall(r"-?\d+", a)]
            assert len(vals) == 128, f"{aliases}: expected 128, got {len(vals)}"
            nums.append(vals)
        families.append((aliases, upm, nums))

    def arr(v):
        return "Array(" + ", ".join(str(x) for x in v) + ")"

    out = ['package org.jpablo.graphexplorer.graphviz.metrics',
           '',
           '// GENERATED by graphviz/oracle/gen_font_metrics.py — do not edit by hand.',
           '// Data transcribed from Graphviz 13.0.1 lib/common/textspan_lut.c (EPL-2.0).',
           '// Per-character advance widths in (unitsPerEm * 1pt); -1 = unknown.',
           '',
           'final case class FontFamilyMetrics(',
           '    names:      List[String],',
           '    unitsPerEm: Int,',
           '    regular:    Array[Short],',
           '    bold:       Array[Short],',
           '    italic:     Array[Short],',
           '    boldItalic: Array[Short]',
           ')',
           '',
           'object FontMetricsTables:',
           '  val families: List[FontFamilyMetrics] = List(']
    for aliases, upm, nums in families:
        names = ", ".join(f'"{a}"' for a in aliases)
        out.append('    FontFamilyMetrics(')
        out.append(f'      List({names}),')
        out.append(f'      {upm},')
        for label, vals in zip(("regular", "bold", "italic", "boldItalic"), nums):
            sfx = "," if label != "boldItalic" else ""
            out.append(f'      {arr(vals)}.map(_.toShort){sfx}')
        out.append('    ),')
    out.append('  )')
    out.append('')

    dest = pathlib.Path(__file__).resolve().parents[1] / \
        "shared/src/main/scala/org/jpablo/graphexplorer/graphviz/metrics/FontMetricsTables.scala"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out))
    print(f"wrote {dest}")
    print("families:", [a[0][0] for a in families])

if __name__ == "__main__":
    main()
