package org.jpablo.graphexplorer.viewer.formats.dot.ast

import org.jpablo.graphexplorer.viewer.formats.dot.ast.Location.Position
import org.jpablo.graphexplorer.viewer.models.Arrow.arrow
import org.jpablo.graphexplorer.viewer.models.Attributable.idAttributeKey
import org.jpablo.graphexplorer.viewer.models.{Arrow, ViewerGroup, ViewerNode}
import upickle.default.*
import upickle.implicits.key

type EdgeElement = DotNodeId | SubGraph

case class DotAST(
    @key("type")
    tpe:      String,
    children: List[GraphElement],
    id:       Option[String] = None
) derives ReadWriter:
  lazy val allElements: (Set[Arrow], Set[ViewerGroup], Set[ViewerNode]) = this.asSubgraph.allElements

  def asSubgraph: SubGraph = SubGraph(children, id)

object DotAST:
  val empty: DotAST = DotAST("digraph", Nil)

case class Location(start: Position, end: Position) derives ReadWriter

object Location:
  case class Position(offset: Int, line: Int, column: Int) derives ReadWriter

@key("type")
sealed trait GraphElement derives ReadWriter:
  lazy val allViewerNodes: Set[ViewerNode] = this.findAllViewerNodes
  lazy val allNodesIds: Set[String] = allViewerNodes.map(_.id.value)
  lazy val allElements = this.findAllElements

object GraphElement:

  given ReadWriter[EdgeElement] =
    readwriter[ujson.Value].bimap[EdgeElement](
      {
        case s: DotNodeId => writeJs(s)
        case a: SubGraph  => writeJs(a)
      },
      { jsValue =>
        if jsValue("type") == ujson.Str("node_id") then read[DotNodeId](jsValue)
        else read[SubGraph](jsValue)
      }
    )
end GraphElement

@key("newline")
case class Newline() extends GraphElement derives ReadWriter

@key("pad")
case class Pad() extends GraphElement derives ReadWriter

@key("comment")
case class Comment() extends GraphElement derives ReadWriter

@key("attr_stmt")
case class AttrStmt(target: String, attr_list: List[Attr]) extends GraphElement derives ReadWriter

@key("attr")
case class Attr(id: String, @key("eq") attrEq: String | AttrEq) derives ReadWriter:
  def value = attrEq match
    case s: String => s
    case a: AttrEq => a.value

case class AttrEq(value: String, html: Boolean = false) derives ReadWriter

object Attr:
  given ReadWriter[String | AttrEq] =
    readwriter[ujson.Value].bimap[String | AttrEq](
      {
        case s: String => writeJs(s)
        case a: AttrEq => writeJs(a)
      },
      {
        case ujson.Str(s) => s
        case jsValue      => read[AttrEq](jsValue)
      }
    )
end Attr

@key("node_stmt")
case class NodeStmt(node_id: DotNodeId, attr_list: List[Attr]) extends GraphElement derives ReadWriter

@key("edge_stmt")
case class EdgeStmt(
    edge_list: List[EdgeElement],
    attr_list: List[Attr]
) extends GraphElement derives ReadWriter:
  lazy val idAttr: String = attr_list.find(_.id == idAttributeKey).map(_.attrEq.toString).getOrElse("")

  def toGraphElements: List[GraphElement] =
    edge_list.flatMap:
      case n: DotNodeId          => NodeStmt(n, Nil) :: Nil
      case SubGraph(children, _) => children

  /** @return
    *   all arrows generated by the nodes in the edge_list
    */
  def expandArrows: List[(List[GraphElement], Set[Arrow])] =
    // TODO: Handle AttrEq as well (for html labels)
    val attrs = toAttrsMap(attr_list)
    edge_list
      .sliding(2)
      .toList
      .map:
        case List(SubGraph(children, _)) => (children, Set.empty)

        // a -> b =>  a -> b
        case List(DotNodeId(a, _), DotNodeId(b, _)) => (Nil, Set(arrow(a -> b, attrs)))

        // a -> {x y ...}  =>  a -> x, a -> y, ...
        case List(DotNodeId(a, _), sub @ SubGraph(children, _)) =>
          (children, sub.allNodesIds.map(x => arrow(a -> x, attrs)))

        // {x y ...} -> a  =>  x -> a, y -> a, ...
        case List(sub @ SubGraph(children, _), DotNodeId(a, _)) =>
          (children, sub.allNodesIds.map(x => arrow(x -> a, attrs)))

        // {x y ...} -> {a b ...}  =>  x -> a, x -> b, y -> a, y -> b, ...
        case List(sub1 @ SubGraph(children1, _), sub2 @ SubGraph(children2, _)) =>
          (
            children1 ++ children2,
            for
              x <- sub1.allNodesIds
              a <- sub2.allNodesIds
            yield arrow(x -> a, attrs)
          )
        case _ => (Nil, Set.empty)

object EdgeStmt:
  private var idx = 0

  def resetId() =
    idx = 0

  def nextId =
    idx += 1
    idx

end EdgeStmt

@key("node_id")
case class DotNodeId(id: String, port: Option[Port] = None) derives ReadWriter

@key("port")
case class Port(id: String) derives ReadWriter

@key("stmt_sep")
case class StmtSep() extends GraphElement derives ReadWriter

@key("subgraph")
case class SubGraph(children: List[GraphElement], id: Option[String] = None) extends GraphElement derives ReadWriter
